#pragma once

namespace lev
{
	enum BlendEquation
	{
		BLEND_EQUATION_ADD,
		BLEND_EQUATION_SUBTRACT,
		BLEND_EQUATION_REVERSE_SUBTRACT,
		BLEND_EQUATION_MIN,
		BLEND_EQUATION_MAX
	};

	enum BlendFunc
	{
		BLEND_FUNC_ZERO,
		BLEND_FUNC_ONE,
		BLEND_FUNC_SRC_COLOUR,
		BLEND_FUNC_SRC1_COLOUR,
		BLEND_FUNC_ONE_MINUS_SRC_COLOUR,
		BLEND_FUNC_ONE_MINUS_SRC1_COLOUR,
		BLEND_FUNC_DST_COLOUR,
		BLEND_FUNC_ONE_MINUS_DST_COLOUR,
		BLEND_FUNC_SRC_ALPHA,
		BLEND_FUNC_SRC1_ALPHA,
		BLEND_FUNC_ONE_MINUS_SRC_ALPHA,
		BLEND_FUNC_ONE_MINUS_SRC1_ALPHA,
		BLEND_FUNC_DST_ALPHA,
		BLEND_FUNC_ONE_MINUS_DST_ALPHA,
		BLEND_FUNC_CONSTANT_COLOUR,
		BLEND_FUNC_ONE_MINUS_CONSTANT_COLOUR,
		BLEND_FUNC_CONSTANT_ALPHA,
		BLEND_FUNC_ONE_MINUS_CONSTANT_ALPHA
	};

	struct BlendMode
	{
		BlendEquation equation_rgb;
		BlendEquation equation_alpha;
		
		BlendFunc func_src_rgb;
		BlendFunc func_dst_rgb;

		BlendFunc func_src_alpha;
		BlendFunc func_dst_alpha;
	};
}
