#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D o_trail_map;

void main()
{
	ivec2 coords = ivec2(gl_GlobalInvocationID.xy);

	// find sum of all surrounding pixels
	vec3 sum = vec3(0.0);
	for (int i = -1; i <= 1; i++) {
		for (int j = -1; j <= 1; j++) {
			
			ivec2 offset = ivec2(
				coords.x - i,
				coords.y - j
			);
			
			sum += imageLoad(o_trail_map, offset).rgb;
		}
	}
	
	// mix colours
	vec4 col = vec4(imageLoad(o_trail_map, coords).rgb, 1.0);
	vec4 avg = vec4(sum.rgb / 9.0, 1.0);
	vec4 fin = mix(avg, col, 0.925);

	// fade out a bit
	fin *= 0.9975;

	// store into image
	imageStore(o_trail_map, coords, fin);
}
